[project]
site_name = "ruby-prof"
site_url = "https://ruby-prof.github.io/"
site_description = "A profiler for MRI Ruby"
docs_dir = "docs"

nav = [
  { "Home" = "index.md" },
  { "Getting Started" = "getting-started.md" },
  { "Advanced Usage" = "advanced-usage.md" },
  { "Reports" = "reports.md" },
  { "Profiling Rails" = "profiling-rails.md" },
  { "Architecture" = "architecture.md" },
  { "Changelog" = "changelog.md" },
]
